run

diff --git a/.github/workflows/deploy-report.yml b/.github/workflows/deploy-report.yml
--- a/.github/workflows/deploy-report.yml
+++ b/.github/workflows/deploy-report.yml
@@ -24,15 +24,23 @@ jobs:
       - name: Run Cypress Tests
         run: npm run test:desktop:headless || true
 
-      - name: Clear previous cache
+      - name: Verify index.html exists
         run: |
-          rm -rf ./cypress/reports/index.html
+          if [ ! -f ./cypress/reports/index.html ]; then
+            echo "index.html file not found! Check your report generation step."
+            exit 1
+          fi
+
+      - name: List generated files
+        run: |
+          ls -la ./cypress/reports
 
       - name: Deploy Report
         uses: peaceiris/actions-gh-pages@v3
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: ./cypress/reports
+
 
 
 
